/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author neON
 */
public class PanelInicioSesion extends javax.swing.JPanel {

    private final FramePrincipal frame;

    /**
     * Creates new form PanelInicioSesion
     * @param frame Es la variable del jframe donde añadimos este panel.
     *
     */
    public PanelInicioSesion(FramePrincipal frame){
        this.frame = frame;
        initComponents();
        //super.setBounds(FramePrincipal.dimensiones);
       // this.insertarAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonLoguear = new javax.swing.JButton();
        textPass = new javax.swing.JPasswordField();
        labelPass = new javax.swing.JLabel();
        textUser = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));

        panelCabecera.setBackground(new java.awt.Color(102, 204, 255));
        panelCabecera.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCabecera.setPreferredSize(new java.awt.Dimension(685, 76));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buttonLoguear.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        buttonLoguear.setText("Iniciar Sesion");
        buttonLoguear.setFocusPainted(false);
        buttonLoguear.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonLoguear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoguearActionPerformed(evt);
            }
        });

        textPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textPass.setPreferredSize(new java.awt.Dimension(150, 20));

        labelPass.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelPass.setText("Contraseña");

        textUser.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textUser.setPreferredSize(new java.awt.Dimension(150, 20));

        labelUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelUser.setText("Usuario");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLoguear, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraLayout.createSequentialGroup()
                        .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraLayout.createSequentialGroup()
                        .addComponent(labelPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonLoguear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jSeparator2)
        );

        jLabel1.setText("Usuario : admin");

        jLabel2.setText("Contraseña: 1234");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoguearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoguearActionPerformed
        try {
            // TODO add your handling code here:
            if (frame.logear(textUser.getText(), textPass.getPassword())) {
                frame.getPanelesAnteriores().push(this);
                JOptionPane.showMessageDialog(this, "Logging Exitoso");
                Logging usuarioABuscar = new Logging(textUser.getText(), "0000".toCharArray(), 0, false);
                Logging usuario = frame.getArbolDeLogging().buscar(usuarioABuscar);
                int ci = usuario.getCiDelUsuario();
                Empleado empleado = frame.getArbolDeEmpleados().buscar(new Empleado(ci));
                frame.setUsuario(empleado);
                frame.setLogging(usuario);
                PanelPerfil panel = new PanelPerfil(frame);
                frame.addPanel(panel);
                this.setVisible(false);
                this.textUser.setText(null);
                this.textPass.setText(null);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o Contraseña Incorrecta");
            }
        } catch (ExceptionContraseñaNoValida ex) {
            Logger.getLogger(PanelInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(frame, "Contraseña Invalida");
        }
    }//GEN-LAST:event_buttonLoguearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLoguear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPasswordField textPass;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
}
