/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.ExceptionContraseñaNoValida;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author neON
 */
public class PanelLogging extends javax.swing.JPanel {

    private final FramePrincipal frame;

    /**
     * Creates new form PanelLogging
     *
     * @param frame Es la variable del frame donde añadiremos este panel.
     */
    public PanelLogging(FramePrincipal frame) {
        this.frame = frame;
        initComponents();
        //Rectangle r = new Rectangle(FramePrincipal.ANCHO_FRAME, FramePrincipal.ALTO_FRAME);
        //super.setBounds(r);
        this.textNombre.setText(frame.getUsuario().getNombreCompleto());
        this.textUser.setText(frame.getLogging().getUsuario());
        if (frame.getLogging().siEsAdmin()) {
            String contra = frame.charToString(frame.getLogging().getContraseña());
            this.textPass.setText(contra);
        } else {
            this.textPass.setVisible(false);
            this.labelContraseña.setVisible(false);
        }
        if (frame.getUsuario().getFotografiaPersonal() != null) {
            frame.ajustarFotografia(labelFoto, frame.getUsuario().getFotografiaPersonal());
        }
        frame.cargarIconoAtras(iconAtras);
        frame.addPanelesAtras(popupMenuAnterior);
        this.ajustarIconoOjo(buttonOjo1);
        this.ajustarIconoOjo(buttonOjo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuAnterior = new javax.swing.JPopupMenu();
        iconoOjo = new javax.swing.JLabel();
        panelCabecera = new javax.swing.JPanel();
        iconAtras = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        textNombre = new javax.swing.JTextField();
        textUser = new javax.swing.JTextField();
        textPass = new javax.swing.JTextField();
        panelCambiarUsuario = new javax.swing.JPanel();
        labelNuevoUsuario = new javax.swing.JLabel();
        buttonGuardarUsuario = new javax.swing.JButton();
        textNuevoUsuario1 = new javax.swing.JTextField();
        panelCambiarContraseña = new javax.swing.JPanel();
        labelContraseñaActual = new javax.swing.JLabel();
        buttonGuardarContraseña = new javax.swing.JButton();
        textConfirmarPass = new javax.swing.JPasswordField();
        labelNuevoPass = new javax.swing.JLabel();
        labelConfirmarPass = new javax.swing.JLabel();
        textContraseñaActual = new javax.swing.JTextField();
        buttonOjo2 = new javax.swing.JToggleButton();
        buttonOjo1 = new javax.swing.JToggleButton();
        textNuevaContraseña = new javax.swing.JPasswordField();

        iconoOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ojo.png"))); // NOI18N

        setBackground(new java.awt.Color(187, 187, 187));
        setPreferredSize(new java.awt.Dimension(700, 500));

        panelCabecera.setBackground(new java.awt.Color(102, 204, 255));
        panelCabecera.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCabecera.setPreferredSize(new java.awt.Dimension(685, 76));

        iconAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAtras.setText("Atras");
        iconAtras.setPreferredSize(new java.awt.Dimension(50, 50));
        iconAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAtrasMouseClicked(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelUsuario.setText("Usuario");

        labelContraseña.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelContraseña.setText("Contraseña");

        labelFoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setAlignmentX(0.5F);
        labelFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelFoto.setMaximumSize(new java.awt.Dimension(150, 150));
        labelFoto.setMinimumSize(new java.awt.Dimension(50, 50));
        labelFoto.setPreferredSize(new java.awt.Dimension(70, 70));

        labelNombre.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelNombre.setText("Nombre");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        textNombre.setEditable(false);
        textNombre.setBackground(new java.awt.Color(255, 255, 255));
        textNombre.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        textUser.setEditable(false);
        textUser.setBackground(new java.awt.Color(255, 255, 255));
        textUser.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        textPass.setEditable(false);
        textPass.setBackground(new java.awt.Color(255, 255, 255));
        textPass.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(iconAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addComponent(labelContraseña)
                        .addGap(21, 21, 21)
                        .addComponent(textPass))
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addComponent(labelUsuario)
                        .addGap(47, 47, 47)
                        .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUsuario)
                            .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        panelCambiarUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cambio de Nombre de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 12))); // NOI18N
        panelCambiarUsuario.setMinimumSize(new java.awt.Dimension(685, 166));

        labelNuevoUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelNuevoUsuario.setText("Nuevo Nombre de Usuario");

        buttonGuardarUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        buttonGuardarUsuario.setText("Guardar Cambios");
        buttonGuardarUsuario.setFocusPainted(false);
        buttonGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarUsuarioActionPerformed(evt);
            }
        });

        textNuevoUsuario1.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        textNuevoUsuario1.setPreferredSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout panelCambiarUsuarioLayout = new javax.swing.GroupLayout(panelCambiarUsuario);
        panelCambiarUsuario.setLayout(panelCambiarUsuarioLayout);
        panelCambiarUsuarioLayout.setHorizontalGroup(
            panelCambiarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarUsuarioLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(labelNuevoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCambiarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonGuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNuevoUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCambiarUsuarioLayout.setVerticalGroup(
            panelCambiarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCambiarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNuevoUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonGuardarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCambiarContraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cambio de Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 12))); // NOI18N
        panelCambiarContraseña.setMinimumSize(new java.awt.Dimension(685, 235));
        panelCambiarContraseña.setPreferredSize(new java.awt.Dimension(685, 211));

        labelContraseñaActual.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelContraseñaActual.setText("Contraseña Actual");

        buttonGuardarContraseña.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        buttonGuardarContraseña.setText("Guardar Cambios");
        buttonGuardarContraseña.setFocusPainted(false);
        buttonGuardarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarContraseñaActionPerformed(evt);
            }
        });

        textConfirmarPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textConfirmarPass.setPreferredSize(new java.awt.Dimension(150, 25));

        labelNuevoPass.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelNuevoPass.setText("Nueva Contraseña");

        labelConfirmarPass.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelConfirmarPass.setText("Confirmar Nueva Contraseña");

        textContraseñaActual.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textContraseñaActual.setPreferredSize(new java.awt.Dimension(150, 25));

        buttonOjo2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonOjo2.setFocusPainted(false);
        buttonOjo2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonOjo2.setPreferredSize(new java.awt.Dimension(30, 25));
        buttonOjo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOjo2ActionPerformed(evt);
            }
        });

        buttonOjo1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonOjo1.setFocusPainted(false);
        buttonOjo1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonOjo1.setPreferredSize(new java.awt.Dimension(30, 25));
        buttonOjo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOjo1ActionPerformed(evt);
            }
        });

        textNuevaContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textNuevaContraseña.setPreferredSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout panelCambiarContraseñaLayout = new javax.swing.GroupLayout(panelCambiarContraseña);
        panelCambiarContraseña.setLayout(panelCambiarContraseñaLayout);
        panelCambiarContraseñaLayout.setHorizontalGroup(
            panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarContraseñaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelContraseñaActual)
                    .addComponent(labelNuevoPass)
                    .addComponent(labelConfirmarPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCambiarContraseñaLayout.createSequentialGroup()
                        .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textConfirmarPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textContraseñaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonGuardarContraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonOjo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCambiarContraseñaLayout.createSequentialGroup()
                        .addComponent(textNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonOjo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCambiarContraseñaLayout.setVerticalGroup(
            panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textContraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCambiarContraseñaLayout.createSequentialGroup()
                        .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNuevoPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textConfirmarPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelConfirmarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonOjo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonGuardarContraseña))
                    .addComponent(buttonOjo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(panelCambiarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCambiarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCambiarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajustarIconoOjo(JToggleButton buttonOjo) {
        ImageIcon imageIcon = (ImageIcon) this.iconoOjo.getIcon();
        Image image = imageIcon.getImage(); // transform it
        int width = buttonOjo.getPreferredSize().width, height = buttonOjo.getPreferredSize().width;
        Image newimg = image.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);
        buttonOjo.setIcon(imageIcon);
    }

    private void iconAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAtrasMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) { //Click Izquierdo
            frame.volverPestañaAtras(frame.getUsuario(), frame.getUsuarioAEditar(),
                    frame.getLogging(), false);
            this.setVisible(false);
            this.initComponents();
        }
        if (evt.getButton() == MouseEvent.BUTTON3) {//Click Derecho
            MouseEvent eventoMouse = new MouseEvent(iconAtras, 0, evt.getWhen(),
                    KeyEvent.VK_UNDEFINED, 0, frame.getY() + frame.getY(),
                    1, true);
            popupMenuAnterior.show(evt.getComponent(), evt.getX(), evt.getY() + 20);
            for (int i = 0; i < this.popupMenuAnterior.getComponentCount(); i++) {
            }
        }
    }//GEN-LAST:event_iconAtrasMouseClicked

    private void buttonGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            char[] contraseña = JOptionPane.showInputDialog("Introducir Contraseña").toCharArray();
            if (frame.logear(frame.getLogging().getUsuario(), contraseña)) {
                frame.getLogging().setUsuario(textNuevoUsuario1.getText());
                this.resetPanelUsuario();
            } else {
                JOptionPane.showMessageDialog(frame, "Contraseña incorrecta");
            }
        } catch (ExceptionContraseñaNoValida ex) {
            JOptionPane.showMessageDialog(frame, "Contraseña Invalida");
        }
    }//GEN-LAST:event_buttonGuardarUsuarioActionPerformed

    private void buttonOjo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOjo2ActionPerformed
        // TODO add your handling code here:
        char x = buttonOjo2.isSelected() ? (char) 0 :'●' ;
        this.textConfirmarPass.setEchoChar(x);
    }//GEN-LAST:event_buttonOjo2ActionPerformed

    private void buttonOjo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOjo1ActionPerformed
        // TODO add your handling code here:
        //● para ocultar contraseña,0 para mostrarla
        char x = buttonOjo1.isSelected() ? (char) 0 :'●' ;
        this.textNuevaContraseña.setEchoChar(x);
    }//GEN-LAST:event_buttonOjo1ActionPerformed

    private void buttonGuardarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarContraseñaActionPerformed
        // TODO add your handling code here:
        try {
            char[] contraseñaActual = textContraseñaActual.getText().toCharArray();
            if (frame.logear(frame.getLogging().getUsuario(), contraseñaActual)) {
                if (Arrays.equals(textNuevaContraseña.getPassword(), textConfirmarPass.getPassword())) {
                    frame.getLogging().setContraseña(textNuevaContraseña.getPassword());
                    this.resetPanelContraseña();
                } else {
                    JOptionPane.showMessageDialog(frame, "Las contraseñas no coinciden");
                }
            } else {
                JOptionPane.showMessageDialog(frame, "Contraseña Actual Invalida");
            }
        } catch (ExceptionContraseñaNoValida ex) {
            JOptionPane.showMessageDialog(frame, "Contraseña Invalida");
        }
    }//GEN-LAST:event_buttonGuardarContraseñaActionPerformed

    private void resetPanelContraseña() {
        this.textContraseñaActual.setText(null);
        this.textNuevaContraseña.setText(null);
        this.textConfirmarPass.setText(null);
    }

    private void resetPanelUsuario() {
        this.textNuevoUsuario1.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGuardarContraseña;
    private javax.swing.JButton buttonGuardarUsuario;
    private javax.swing.JToggleButton buttonOjo1;
    private javax.swing.JToggleButton buttonOjo2;
    private javax.swing.JLabel iconAtras;
    private javax.swing.JLabel iconoOjo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelConfirmarPass;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelContraseñaActual;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNuevoPass;
    private javax.swing.JLabel labelNuevoUsuario;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelCambiarContraseña;
    private javax.swing.JPanel panelCambiarUsuario;
    private javax.swing.JPopupMenu popupMenuAnterior;
    private javax.swing.JPasswordField textConfirmarPass;
    private javax.swing.JTextField textContraseñaActual;
    private javax.swing.JTextField textNombre;
    private javax.swing.JPasswordField textNuevaContraseña;
    private javax.swing.JTextField textNuevoUsuario1;
    private javax.swing.JTextField textPass;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
}
