/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.ExceptionContraseñaNoValida;
import arbolbin.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author neON
 */
public class PanelEleccionArbol extends javax.swing.JPanel {

    private final FramePrincipal frame;

    /**
     * Creates new form PanelEleccionArbol
     * @param frame Es la variable del frame donde añadiremos este el panel.
     */
    public PanelEleccionArbol(FramePrincipal frame) {
        this.frame = frame;
        initComponents();
        //super.setBounds(r);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrupoArboles = new javax.swing.ButtonGroup();
        panelContenedor = new javax.swing.JPanel();
        buttonElegirArbol = new javax.swing.JButton();
        buttonArB = new javax.swing.JRadioButton();
        buttonAMV = new javax.swing.JRadioButton();
        buttonABB = new javax.swing.JRadioButton();
        buttonAVL = new javax.swing.JRadioButton();
        labelTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));

        panelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelContenedor.setPreferredSize(new java.awt.Dimension(350, 300));

        buttonElegirArbol.setBackground(new java.awt.Color(255, 255, 255));
        buttonElegirArbol.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonElegirArbol.setText("Elegir");
        buttonElegirArbol.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonElegirArbol.setFocusPainted(false);
        buttonElegirArbol.setPreferredSize(new java.awt.Dimension(700, 75));
        buttonElegirArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElegirArbolActionPerformed(evt);
            }
        });

        buttonArB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGrupoArboles.add(buttonArB);
        buttonArB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonArB.setText("Arbol B");
        buttonArB.setFocusPainted(false);
        buttonArB.setPreferredSize(new java.awt.Dimension(700, 70));

        buttonAMV.setBackground(buttonArB.getBackground());
        buttonGrupoArboles.add(buttonAMV);
        buttonAMV.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonAMV.setText("Arbol M-Vias");
        buttonAMV.setFocusPainted(false);
        buttonAMV.setPreferredSize(new java.awt.Dimension(700, 70));

        buttonABB.setBackground(buttonArB.getBackground());
        buttonGrupoArboles.add(buttonABB);
        buttonABB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonABB.setSelected(true);
        buttonABB.setText("Arbol Busqueda Binaria");
        buttonABB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonABB.setFocusPainted(false);
        buttonABB.setPreferredSize(new java.awt.Dimension(700, 70));

        buttonAVL.setBackground(buttonArB.getBackground());
        buttonGrupoArboles.add(buttonAVL);
        buttonAVL.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonAVL.setText("AVL");
        buttonAVL.setFocusPainted(false);
        buttonAVL.setPreferredSize(new java.awt.Dimension(700, 70));

        labelTitulo.setBackground(new java.awt.Color(217, 225, 233));
        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Tipo de Arbol Busqueda");
        labelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelTitulo.setOpaque(true);
        labelTitulo.setPreferredSize(new java.awt.Dimension(700, 75));
        labelTitulo.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonABB, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
            .addComponent(buttonAMV, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(buttonArB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(buttonElegirArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(buttonAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonABB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAMV, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonArB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElegirArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonElegirArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElegirArbolActionPerformed
        // TODO add your handling code here:
        if (buttonABB.isSelected()) {
            frame.setArbolEmpl(new ArbolBinarioBusqueda<>());
            frame.setArbolLogg(new ArbolBinarioBusqueda<>());
        } else if (buttonAVL.isSelected()) {
            frame.setArbolEmpl(new AVL<>());
            frame.setArbolLogg(new AVL<>());
        } else if (buttonAMV.isSelected()) {
            String test1 = JOptionPane.showInputDialog("Por favor introduzca el orden del arbol: ");
            int orden = Integer.parseInt(test1);
            try {
                frame.setArbolEmpl(new ArbolMViasBusqueda<>(orden));
                frame.setArbolLogg(new ArbolMViasBusqueda<>(orden));
            } catch (ExcepcionOrdenInvalido ex) {
                JOptionPane.showMessageDialog(frame, "Orden del arbol invalido");
            }
        } else if (buttonArB.isSelected()) {
            String test1 = JOptionPane.showInputDialog("Por favor introduzca el orden del arbol: ");
            int orden = Integer.parseInt(test1);
            try {
                frame.setArbolEmpl(new ArbolB<>(orden));
                frame.setArbolLogg(new ArbolB<>(orden));
            } catch (ExcepcionOrdenInvalido ex) {
                JOptionPane.showMessageDialog(frame, "Orden del arbol invalido");
            }
        }
        if (frame.getArbolDeEmpleados() != null) {
            try {
                PanelInicioSesion panel = new PanelInicioSesion(frame);
                frame.cargarDatos();
                frame.addPanel(panel);
                this.setVisible(false);
            } catch (ExceptionContraseñaNoValida ex) {
                Logger.getLogger(PanelEleccionArbol.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonElegirArbolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buttonABB;
    private javax.swing.JRadioButton buttonAMV;
    private javax.swing.JRadioButton buttonAVL;
    private javax.swing.JRadioButton buttonArB;
    private javax.swing.JButton buttonElegirArbol;
    private javax.swing.ButtonGroup buttonGrupoArboles;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
