/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.event.*;
import java.text.DateFormat;
import java.util.*;
import javax.swing.JPanel;

/**
 *
 * @author neON
 */
public class PanelPerfil extends javax.swing.JPanel {

    private final FramePrincipal frame;

    /**
     * Creates new form PanelPerfilEmpleado
     * @param frame Es la variable del frame donde añadiremos este panel.
     */
    public PanelPerfil(FramePrincipal frame) {
        this.frame = frame;
        initComponents();
        //super.setBounds(FramePrincipal.dimensiones);
        if (!frame.getLogging().siEsAdmin()) {
            buttonLista.setVisible(false);
        }
        this.cargarPerfil();
        frame.cargarIconoAtras(iconAtras);
        frame.addPanelesAtras(popupMenuAnterior);
        buttonDatos.setText("<html>Cambiar Datos<br>Sesion<html>");
        buttonLista.setText("<html>Lista de<br>Empleados<html>");
    }

    private void cargarPerfil() {
        if (frame.getUsuario().getFotografiaPersonal() != null) {
            frame.ajustarFotografia(labelFoto, frame.getUsuario().getFotografiaPersonal());
        }
        textEstadoCivil.setText(frame.getUsuario().getEstadoCivil());
        textDireccion.setText(frame.getUsuario().getDireccion());
        textEdad.setText(String.valueOf(frame.getUsuario().getEdad()) + " años");
        textCargo.setText(frame.getUsuario().getCargo());
        textPais.setText(frame.getUsuario().getPaisOrigen());
        textSueldoNeto.setText(String.valueOf(frame.getUsuario().getSueldoMensual()) + " Bs");
        textNombre.setText(frame.getUsuario().getNombreCompleto());
        labelCI.setText(String.valueOf(frame.getUsuario().getCI())
                + " " + frame.getUsuario().getCiExpedicion());
        textCorreo.setText(frame.getUsuario().getCorreo());
        textTelefono.setText(String.valueOf(
                frame.getUsuario().getNumeroTelefonico()));
        textUsuario.setText(frame.getLogging().getUsuario());
        textCargo.setText(frame.getUsuario().getCargo());
        Date date = frame.getUsuario().getFechaNac();
        textFechaNac.setText(DateFormat.getDateInstance().format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuAnterior = new javax.swing.JPopupMenu();
        fotoAtras = new javax.swing.JLabel();
        buttonCerrarSesion = new javax.swing.JButton();
        panelCabecera = new javax.swing.JPanel();
        iconAtras = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        textNombre = new javax.swing.JTextField();
        textUsuario = new javax.swing.JTextField();
        labelCI = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        textCargo = new javax.swing.JTextField();
        textCorreo = new javax.swing.JTextField();
        textPais = new javax.swing.JTextField();
        textEstadoCivil = new javax.swing.JTextField();
        textSueldoNeto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDireccion = new javax.swing.JTextArea();
        textFechaNac = new javax.swing.JFormattedTextField();
        textEdad = new javax.swing.JTextField();
        buttonDatos = new javax.swing.JButton();
        buttonLista = new javax.swing.JButton();
        labelSuedoNeto = new javax.swing.JLabel();
        labelCi = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelPais = new javax.swing.JLabel();
        labelEstadoCivil = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelFechaNac = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        popupMenuAnterior.setBorderPainted(false);

        fotoAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconAtras.png"))); // NOI18N
        fotoAtras.setPreferredSize(new java.awt.Dimension(50, 50));

        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));

        buttonCerrarSesion.setText("Cerrar Sesion");
        buttonCerrarSesion.setFocusPainted(false);
        buttonCerrarSesion.setPreferredSize(new java.awt.Dimension(105, 50));
        buttonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarSesionActionPerformed(evt);
            }
        });

        panelCabecera.setBackground(new java.awt.Color(102, 204, 255));
        panelCabecera.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCabecera.setPreferredSize(new java.awt.Dimension(685, 76));

        iconAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAtras.setText("Atras");
        iconAtras.setPreferredSize(new java.awt.Dimension(50, 50));
        iconAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAtrasMouseClicked(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelUsuario.setLabelFor(textUsuario);
        labelUsuario.setText("Usuario");

        labelFoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setAlignmentX(0.5F);
        labelFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelFoto.setMaximumSize(new java.awt.Dimension(150, 150));
        labelFoto.setMinimumSize(new java.awt.Dimension(50, 50));
        labelFoto.setPreferredSize(new java.awt.Dimension(70, 70));

        labelNombre.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelNombre.setLabelFor(textNombre);
        labelNombre.setText("Nombre");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        textNombre.setEditable(false);
        textNombre.setBackground(new java.awt.Color(255, 255, 255));
        textNombre.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        textUsuario.setEditable(false);
        textUsuario.setBackground(new java.awt.Color(255, 255, 255));
        textUsuario.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(iconAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario))
                .addGap(26, 26, 26))
        );

        labelCI.setEditable(false);
        labelCI.setBackground(new java.awt.Color(255, 255, 255));
        labelCI.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelCI.setPreferredSize(new java.awt.Dimension(170, 25));

        textTelefono.setEditable(false);
        textTelefono.setBackground(new java.awt.Color(255, 255, 255));
        textTelefono.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textTelefono.setPreferredSize(new java.awt.Dimension(170, 25));

        textCargo.setEditable(false);
        textCargo.setBackground(new java.awt.Color(255, 255, 255));
        textCargo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textCargo.setPreferredSize(new java.awt.Dimension(170, 25));

        textCorreo.setEditable(false);
        textCorreo.setBackground(new java.awt.Color(255, 255, 255));
        textCorreo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textCorreo.setPreferredSize(new java.awt.Dimension(170, 25));

        textPais.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textPais.setPreferredSize(new java.awt.Dimension(170, 25));

        textEstadoCivil.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textEstadoCivil.setPreferredSize(new java.awt.Dimension(170, 25));

        textSueldoNeto.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textSueldoNeto.setPreferredSize(new java.awt.Dimension(170, 25));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 70));

        textDireccion.setEditable(false);
        textDireccion.setColumns(10);
        textDireccion.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textDireccion.setRows(3);
        jScrollPane1.setViewportView(textDireccion);

        textFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        textFechaNac.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textFechaNac.setPreferredSize(new java.awt.Dimension(170, 25));

        textEdad.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textEdad.setPreferredSize(new java.awt.Dimension(170, 25));

        buttonDatos.setText("Datos");
        buttonDatos.setFocusPainted(false);
        buttonDatos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDatos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        buttonDatos.setPreferredSize(new java.awt.Dimension(105, 50));
        buttonDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDatosActionPerformed(evt);
            }
        });

        buttonLista.setText("Empleados");
        buttonLista.setFocusPainted(false);
        buttonLista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonLista.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        buttonLista.setPreferredSize(new java.awt.Dimension(105, 50));
        buttonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListaActionPerformed(evt);
            }
        });

        labelSuedoNeto.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelSuedoNeto.setText("Sueldo Neto");

        labelCi.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelCi.setText("CI");

        labelTelefono.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelTelefono.setText("Telefono");

        labelCargo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelCargo.setText("Cargo");

        labelCorreo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelCorreo.setText("Correo");

        labelPais.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelPais.setText("Pais");

        labelEstadoCivil.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelEstadoCivil.setText("Estado Civil");

        labelDireccion.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelDireccion.setText("Direccion");

        labelEdad.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelEdad.setText("Edad");

        labelFechaNac.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelFechaNac.setText("Fecha de Nacimiento");

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSuedoNeto)
                            .addComponent(labelEstadoCivil)
                            .addComponent(labelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFechaNac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSueldoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCi)
                                    .addComponent(labelCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCorreo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCargo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textSueldoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelSuedoNeto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEstadoCivil))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textPais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPais))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelFechaNac))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelEdad)))
                                    .addComponent(labelDireccion)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(buttonDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonLista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(68, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed
        // TODO add your handling code here:
        frame.getPanelesAnteriores().pop();
        this.setVisible(false);
        JPanel panel = new PanelInicioSesion(frame);
        //JPanel panel = frame.getPanelesAnteriores().pop();
        frame.addPanel(panel);
        this.initComponents();
    }//GEN-LAST:event_buttonCerrarSesionActionPerformed

    private void iconAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAtrasMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) { //Click Izquierdo
            this.setVisible(false);
            frame.volverPestañaAtras(frame.getUsuario(), frame.getUsuarioAEditar(),
                    frame.getLogging(), false);
            //this.initComponents();
        }
        if (evt.getButton() == MouseEvent.BUTTON3) {//Click Derecho
            MouseEvent eventoMouse = new MouseEvent(iconAtras, 0, evt.getWhen(),
                    KeyEvent.VK_UNDEFINED, 0, frame.getY() + frame.getY(),
                    1, true);
            popupMenuAnterior.show(evt.getComponent(), evt.getX(), evt.getY() + 20);
            for (int i = 0; i < this.popupMenuAnterior.getComponentCount(); i++) {
            }
        }
    }//GEN-LAST:event_iconAtrasMouseClicked

    private void buttonListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListaActionPerformed
        // TODO add your handling code here:
        frame.getPanelesAnteriores().push(this);
        PanelLista panelAdd = new PanelLista(frame);
        frame.addPanel(panelAdd);
        this.setVisible(false);
        //this.initComponents();
        this.initComponents();
    }//GEN-LAST:event_buttonListaActionPerformed

    private void buttonDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDatosActionPerformed
        // TODO add your handling code here:
        frame.getPanelesAnteriores().push(this);
        PanelLogging panelAdd;
        panelAdd = new PanelLogging(frame);
        frame.setLoggingAEditar(frame.getLogging());
        frame.addPanel(panelAdd);
        this.setVisible(false);
        //this.initComponents();
    }//GEN-LAST:event_buttonDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrarSesion;
    private javax.swing.JButton buttonDatos;
    private javax.swing.JButton buttonLista;
    private javax.swing.JLabel fotoAtras;
    private javax.swing.JLabel iconAtras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField labelCI;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelCi;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelEstadoCivil;
    private javax.swing.JLabel labelFechaNac;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPais;
    private javax.swing.JLabel labelSuedoNeto;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPopupMenu popupMenuAnterior;
    private javax.swing.JTextField textCargo;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextArea textDireccion;
    private javax.swing.JTextField textEdad;
    private javax.swing.JTextField textEstadoCivil;
    private javax.swing.JFormattedTextField textFechaNac;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPais;
    private javax.swing.JTextField textSueldoNeto;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
