/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.*;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author neON
 */
public class PanelRegistro extends javax.swing.JPanel {

    private final FramePrincipal frame;
    private final boolean editando;
    private boolean fotoAñadida;
    private ImageIcon fotoPerfil;

    /**
     * Creates new form PanelRegistro
     *
     * @param frame Es la variable del frame donde añadiremos este panel
     * @param editando Es la bandera que indica si estamos editando o no un
     * empleado.
     */
    public PanelRegistro(FramePrincipal frame, boolean editando) {
        this.frame = frame;
        this.editando = editando;
        initComponents();
        frame.cargarIconoAtras(iconAtras);
        frame.addPanelesAtras(popupMenuAnterior);
        this.cargarComboAños();
        this.actualizarComboDias();
        if (this.editando) {
            this.labelTitulo.setText("Editar Empleado");
            this.buttonRegistro.setText("Guardar");
            this.loadEmpleado(frame.getUsuarioAEditar());
            this.fotoPerfil = frame.getUsuarioAEditar().getFotografiaPersonal();
            this.comboAño.setEnabled(false);
            this.comboMes.setEnabled(false);
            this.comboDia.setEnabled(false);
            this.textCi.setEnabled(false);
            this.comboCiExp.setEnabled(false);
        } else {
            this.fotoPerfil = null;
            this.labelTitulo.setText("Registrar Nuevo Empleado");
            this.cargarFotoPorDefecto();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuAnterior = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        fotoPerfilFija = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        panelCabecera = new javax.swing.JPanel();
        iconAtras = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        comboCiExp = new javax.swing.JComboBox<>();
        labelCorreo = new javax.swing.JLabel();
        labelSueldo = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDireccion = new javax.swing.JTextArea();
        textCi = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textApellP = new javax.swing.JTextField();
        textApellM = new javax.swing.JTextField();
        textCorreo = new javax.swing.JTextField();
        labelCi = new javax.swing.JLabel();
        textSueldo = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellP = new javax.swing.JLabel();
        labelApellM = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelSexo = new javax.swing.JPanel();
        buttonSexoF = new javax.swing.JRadioButton();
        buttonSexoNoId = new javax.swing.JRadioButton();
        buttonSexoM = new javax.swing.JRadioButton();
        labelFechaNac = new javax.swing.JLabel();
        comboCargo = new javax.swing.JComboBox<>();
        labelPais = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        labelEstCivil = new javax.swing.JLabel();
        comboPais = new javax.swing.JComboBox<>();
        comboEstadoCivil = new javax.swing.JComboBox<>();
        labelFoto = new javax.swing.JLabel();
        buttonRegistro = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        panelFecha = new javax.swing.JPanel();
        comboDia = new javax.swing.JComboBox<>();
        comboAño = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();

        fotoPerfilFija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perfil(Default).jpg"))); // NOI18N
        fotoPerfilFija.setText("Foto Perfil");

        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));

        panelCabecera.setBackground(new java.awt.Color(102, 204, 255));
        panelCabecera.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCabecera.setPreferredSize(new java.awt.Dimension(685, 76));

        iconAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAtras.setText("Atras");
        iconAtras.setPreferredSize(new java.awt.Dimension(50, 50));
        iconAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAtrasMouseClicked(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        labelTitulo.setText("Registro o Editar Empleado");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(iconAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelTitulo)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        comboCiExp.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        comboCiExp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SC", "LP", "CC", "BN", "PN", "TJ", "CH", "OR", "PT", "NA" }));
        comboCiExp.setPreferredSize(new java.awt.Dimension(46, 25));

        labelCorreo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelCorreo.setText("Correo");

        labelSueldo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelSueldo.setText("Sueldo por Hora");

        labelDireccion.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelDireccion.setText("Direccion");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 81));

        textDireccion.setColumns(20);
        textDireccion.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textDireccion.setRows(5);
        textDireccion.setWrapStyleWord(true);
        textDireccion.setPreferredSize(new java.awt.Dimension(150, 80));
        jScrollPane1.setViewportView(textDireccion);

        textCi.setPreferredSize(new java.awt.Dimension(150, 25));
        textCi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCitextTelefonoKeyTyped(evt);
            }
        });

        textTelefono.setPreferredSize(new java.awt.Dimension(150, 25));
        textTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTelefonoKeyTyped(evt);
            }
        });

        textNombre.setPreferredSize(new java.awt.Dimension(150, 25));
        textNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNombreKeyTyped(evt);
            }
        });

        textApellP.setPreferredSize(new java.awt.Dimension(150, 25));
        textApellP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textApellPtextNombreKeyTyped(evt);
            }
        });

        textApellM.setPreferredSize(new java.awt.Dimension(150, 25));
        textApellM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textApellMtextNombreKeyTyped(evt);
            }
        });

        textCorreo.setPreferredSize(new java.awt.Dimension(150, 25));

        labelCi.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelCi.setText("CI");

        textSueldo.setMinimumSize(new java.awt.Dimension(120, 25));
        textSueldo.setPreferredSize(new java.awt.Dimension(150, 25));
        textSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSueldotextTelefonoKeyTyped(evt);
            }
        });

        labelTelefono.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelTelefono.setText("Telefono");

        labelNombre.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelNombre.setText("Nombre");

        labelApellP.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelApellP.setText("Apellido Paterno");

        labelApellM.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelApellM.setText("Apellido Materno");

        jSeparator1.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        panelSexo.setBackground(new java.awt.Color(255, 255, 255));
        panelSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 11))); // NOI18N

        buttonSexoF.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(buttonSexoF);
        buttonSexoF.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        buttonSexoF.setText("Femenino");

        buttonSexoNoId.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(buttonSexoNoId);
        buttonSexoNoId.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        buttonSexoNoId.setSelected(true);
        buttonSexoNoId.setText("No Especificado");

        buttonSexoM.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(buttonSexoM);
        buttonSexoM.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        buttonSexoM.setText("Masculino");

        javax.swing.GroupLayout panelSexoLayout = new javax.swing.GroupLayout(panelSexo);
        panelSexo.setLayout(panelSexoLayout);
        panelSexoLayout.setHorizontalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addGroup(panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSexoNoId)
                    .addComponent(buttonSexoF)
                    .addComponent(buttonSexoM))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSexoLayout.setVerticalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addComponent(buttonSexoM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSexoF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSexoNoId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelFechaNac.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelFechaNac.setText("Fecha de Nacimiento");

        comboCargo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Sub Gerente", "Administrador de Sistemas", "Ejecutivo", "Secretario General", "Secretario de Administracion", "Empleado", "Recepcionista", "Asistente Personal" }));

        labelPais.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelPais.setText("Pais de Origen");

        labelCargo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelCargo.setText("Cargo");

        labelEstCivil.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelEstCivil.setText("Estado Civil");

        comboPais.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        comboPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Ciudad del Vaticano", "Colombia", "Comoras", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guyana", "Guinea", "Guinea ecuatorial", "Guinea-Bisáu", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Centroafricana", "República Checa", "República del Congo", "República Democrática del Congo", "República Dominicana", "República Sudafricana", "Ruanda", "Rumanía", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Suazilandia", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue" }));
        comboPais.setSelectedIndex(22);

        comboEstadoCivil.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        comboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero/a", "Comprometido/a", "En Relación", "Casado/a", "Unión libre o unión de hecho", "Separado/a", "Divorciado/a", "Viudo/a", "Noviazgo" }));

        labelFoto.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setText("Foto");
        labelFoto.setToolTipText("");
        labelFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        labelFoto.setPreferredSize(new java.awt.Dimension(100, 100));
        labelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFotoMouseClicked(evt);
            }
        });

        buttonRegistro.setText("Registrar");
        buttonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistroActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        panelFecha.setLayout(null);

        comboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        panelFecha.add(comboDia);
        comboDia.setBounds(0, 0, 50, 22);

        comboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1970" }));
        comboAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAñoActionPerformed(evt);
            }
        });
        panelFecha.add(comboAño);
        comboAño.setBounds(100, 0, 60, 22);

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" }));
        comboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesActionPerformed(evt);
            }
        });
        panelFecha.add(comboMes);
        comboMes.setBounds(50, 0, 50, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDireccion)
                    .addComponent(labelSueldo)
                    .addComponent(labelCorreo)
                    .addComponent(labelApellM)
                    .addComponent(labelApellP)
                    .addComponent(labelNombre)
                    .addComponent(labelTelefono)
                    .addComponent(labelCi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textCi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCiExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textApellM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textApellP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textSueldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFechaNac)
                    .addComponent(labelPais)
                    .addComponent(comboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEstCivil)
                    .addComponent(comboPais, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCargo)
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCi)
                            .addComponent(comboCiExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textApellP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textApellM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCorreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDireccion)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSueldo))
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFechaNac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(labelPais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEstCivil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCargo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonRegistro)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iconAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAtrasMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            //Click Izquierdo
            frame.volverPestañaAtras(frame.getUsuario(), frame.getUsuarioAEditar(),
                    frame.getLogging(), editando);
            this.setVisible(false);
            this.initComponents();
        }
        if (evt.getButton() == MouseEvent.BUTTON3) {//Click Derecho
            MouseEvent eventoMouse = new MouseEvent(iconAtras, 0, evt.getWhen(),
                    KeyEvent.VK_UNDEFINED, 0, frame.getY() + frame.getY(),
                    1, true);
            popupMenuAnterior.show(evt.getComponent(), evt.getX(), evt.getY() + 20);
            for (int i = 0; i < this.popupMenuAnterior.getComponentCount(); i++) {
            }
        }
    }//GEN-LAST:event_iconAtrasMouseClicked

    private void textCitextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCitextTelefonoKeyTyped
        // TODO add your handling code here:
        frame.añadirSoloDigitos(evt);
    }//GEN-LAST:event_textCitextTelefonoKeyTyped

    private void textTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelefonoKeyTyped
        // TODO add your handling code here:
        frame.añadirSoloDigitos(evt);
    }//GEN-LAST:event_textTelefonoKeyTyped

    private void textNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNombreKeyTyped
        // TODO add your handling code here:
        frame.añadirSoloLetras(evt);
    }//GEN-LAST:event_textNombreKeyTyped

    private void textApellPtextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textApellPtextNombreKeyTyped
        // TODO add your handling code here:
        frame.añadirSoloLetras(evt);
    }//GEN-LAST:event_textApellPtextNombreKeyTyped

    private void textApellMtextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textApellMtextNombreKeyTyped
        // TODO add your handling code here:
        frame.añadirSoloLetras(evt);
    }//GEN-LAST:event_textApellMtextNombreKeyTyped

    private void textSueldotextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSueldotextTelefonoKeyTyped
        // TODO add your handling code here:
        frame.añadirSoloDigitos(evt);
    }//GEN-LAST:event_textSueldotextTelefonoKeyTyped

    private void labelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFotoMouseClicked
        // TODO add your handling code here:
        this.labelFoto.setText(null);
        JFileChooser selector = new JFileChooser();
        selector.setAcceptAllFileFilterUsed(false);
        selector.addChoosableFileFilter(new FileNameExtensionFilter("All Images Files", "bmp", "dib", "jpg", "jpeg", "png"));
        selector.addChoosableFileFilter(new FileNameExtensionFilter("Bitmap(*.bmp,*.dib)", "bmp", "dib"));
        selector.addChoosableFileFilter(new FileNameExtensionFilter("JPEG(*.jpg,*.jpeg)", "jpg", "jpeg"));
        selector.addChoosableFileFilter(new FileNameExtensionFilter("PNG(*.png)", "png"));
        //selector.setFileFilter(new Filter());
        int estado = selector.showOpenDialog(null);
        File archivoelegido = selector.getSelectedFile();
        String ruta = archivoelegido.getPath();
        if (archivoelegido.exists()) {
            System.out.println("bien");
        } else {
            System.out.println("no bien");
        }
        if (estado == JFileChooser.APPROVE_OPTION);
        {
            System.out.println(ruta);
            ImageIcon imageIcon = new ImageIcon(ruta);
            this.fotoPerfil = imageIcon;
            frame.ajustarFotografia(labelFoto, fotoPerfil);
            this.fotoAñadida = true;
        }
    }//GEN-LAST:event_labelFotoMouseClicked

    private void cargarComboAños() {
        Date año = new Date();
        this.comboAño.removeAllItems();
        for (int i = 0; i <= (año.getYear() - 18); i++) {
            if (i < 50) {
                continue;
            }
            this.comboAño.addItem(String.valueOf(1900 + i));
        }
        int indice = frame.indiceEnComboBox(comboAño, "1970");
        this.comboAño.setSelectedIndex(indice);
    }

    private void cargarFotoPorDefecto() {
        labelFoto.setText(null);
        frame.ajustarFotografia(labelFoto, (ImageIcon) fotoPerfilFija.getIcon());
    }

    private void loadEmpleado(Empleado empleadoEditar) {
        textCi.setText(String.valueOf(empleadoEditar.getCI()));
        textNombre.setText(empleadoEditar.getNombre());
        textApellP.setText(empleadoEditar.getApellPaterno());
        textApellM.setText(empleadoEditar.getApellMaterno());
        textSueldo.setText(String.valueOf(empleadoEditar.getSueldoPorHora()));
        textTelefono.setText(String.valueOf(empleadoEditar.getNumeroTelefonico()));
        int indiceComboEstCivil = frame.indiceEnComboBox(comboEstadoCivil, empleadoEditar.getEstadoCivil());
        comboPais.setSelectedIndex(indiceComboEstCivil);
        textCorreo.setText(empleadoEditar.getCorreo());
        textDireccion.setText(empleadoEditar.getDireccion());
        int indiceComboPais = frame.indiceEnComboBox(comboPais, empleadoEditar.getPaisOrigen());
        comboPais.setSelectedIndex(indiceComboPais);
        switch (empleadoEditar.getSexo()) {
            case "Masculino":
                buttonSexoM.setSelected(true);
                break;
            case "Femenino":
                buttonSexoF.setSelected(true);
                break;
            default:
                buttonSexoNoId.setSelected(true);
                break;
        }
        int indiceComboCargo = frame.indiceEnComboBox(comboCargo, empleadoEditar.getCargo());
        comboCargo.setSelectedIndex(indiceComboCargo);
        int indiceComboCiExp = frame.indiceEnComboBox(comboCiExp, empleadoEditar.getCiExpedicion());
        comboCiExp.setSelectedIndex(indiceComboCiExp);
        if (empleadoEditar.getFotografiaPersonal() != null) {
            labelFoto.setText(null);
            this.fotoAñadida = true;
            frame.ajustarFotografia(labelFoto, empleadoEditar.getFotografiaPersonal());
        }
        Date fecha = empleadoEditar.getFechaNac();
        this.cargarFechaDeEmpleado(fecha);
    }

    private boolean verificacionCamposLlenos() {
        boolean b;
        if (!this.editando) {
            b = !"".equals(this.textCi.getText());
        } else {
            b = true;
        }
        b = b ? fotoAñadida : b;
        b = b ? !"".equals(this.textNombre.getText()) : b;
        b = b ? !"".equals(this.textApellP.getText()) : b;
        b = b ? !"".equals(this.textApellM.getText()) : b;
        b = b ? !"".equals(this.textCorreo.getText()) : b;
        b = b ? !"".equals(this.textDireccion.getText()) : b;
        b = b ? !"".equals(this.textSueldo.getText()) : b;
        b = b ? !"".equals(this.textTelefono.getText()) : b;
        return b;
    }

    private Empleado nuevoEmpleado() {
        int ci = Integer.parseInt(textCi.getText());
        String ciExp = comboCiExp.getItemAt(comboCiExp.getSelectedIndex());
        int telefono = Integer.parseInt(textTelefono.getText());
        String nombre = textNombre.getText();
        String apellP = textApellP.getText();
        String apellM = textApellM.getText();
        String correo = textCorreo.getText();
        String pais = comboPais.getItemAt(comboPais.getSelectedIndex());
        String sexo;
        if (buttonSexoM.isSelected()) {
            sexo = buttonSexoM.getText();
        } else if (buttonSexoF.isSelected()) {
            sexo = buttonSexoF.getText();
        } else {
            sexo = buttonSexoNoId.getText();
        }
        int sueldo = Integer.parseInt(textSueldo.getText());
        String cargo = comboCargo.getItemAt(comboCargo.getSelectedIndex());
        String estCivil = comboEstadoCivil.getItemAt(comboEstadoCivil.getSelectedIndex());
        String direccion = textDireccion.getText();
        Date fechaNac = this.fechaSeleccionada();
        Date fechaEntrada = new Date();
        ImageIcon fotoPersonal = this.fotoPerfil;
        Empleado persona = new Empleado(ci, ciExp, telefono, nombre, apellP, apellM, correo, pais, sexo, sueldo, cargo,
                estCivil, direccion, fechaNac, fechaEntrada, fotoPersonal);
        return persona;
    }

    private void setDatosEmpleado(Empleado persona) {
        persona.setApellMaterno(textApellM.getText());
        persona.setApellPaterno(textApellP.getText());
        persona.setCargo(comboCargo.getItemAt(comboCargo.getSelectedIndex()));
        persona.setCorreo(textCorreo.getText());
        persona.setDireccion(textDireccion.getText());
        persona.setEstadoCivil(comboEstadoCivil.getItemAt(comboEstadoCivil.getSelectedIndex()));
        persona.setNombre(textNombre.getText());
        persona.setNumeroTelefonico(Integer.parseInt(textTelefono.getText()));
        persona.setSueldoPorHora(Integer.parseInt(textSueldo.getText()));
        persona.setFotografiaPersonal(this.fotoPerfil);
        String sexo;
        if (buttonSexoM.isSelected()) {
            sexo = buttonSexoM.getText();
        } else if (buttonSexoF.isSelected()) {
            sexo = buttonSexoF.getText();
        } else {
            sexo = buttonSexoNoId.getText();
        }
        persona.setSexo(sexo);
    }

    private void buttonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistroActionPerformed
        // TODO add your handling code here:
        if (this.verificacionCamposLlenos()) {
            if (this.editando) {
                this.setDatosEmpleado(frame.getUsuarioAEditar());
            } else {
                Empleado nuevo = this.nuevoEmpleado();
                String user = String.valueOf(nuevo.getCI());
                char[] pass = "0000".toCharArray();
                Logging nuevoLogg = new Logging(user, pass, nuevo.getCI(), false);
                frame.getArbolDeEmpleados().insertar(nuevo,nuevo);
                frame.getArbolDeLogging().insertar(nuevoLogg,nuevoLogg);
            }
            frame.volverPestañaAtras(frame.getUsuario(), frame.getUsuarioAEditar(),
                    frame.getLogging(), this.editando);
            this.setVisible(false);
            this.initComponents();
        } else {
            try {
                throw new ExceptionFrame(frame, "Faltan Campos a rellenar");
            } catch (ExceptionFrame ex) {
            }
        }
    }//GEN-LAST:event_buttonRegistroActionPerformed

    private Date fechaSeleccionada() {
        int año = comboAño.getSelectedIndex() + 50;
        int mes = comboMes.getSelectedIndex();
        int dia = comboDia.getSelectedIndex() + 1;
        return new Date(año, mes, dia);
    }

    private void cargarFechaDeEmpleado(Date fecha) {
        int año = fecha.getYear() - 50;
        int mes = fecha.getMonth();
        int dia = fecha.getDate() - 1;
        comboAño.setSelectedIndex(año);
        comboMes.setSelectedIndex(mes);
        comboDia.setSelectedIndex(dia);
    }

    private void actualizarComboDias() {
        int año = 1950 + comboAño.getSelectedIndex();
        int mes = comboMes.getSelectedIndex();
        int dias;
        switch (mes) {
            case 0:
            case 2:
            case 4:
            case 6:
            case 7:
            case 9:
            case 11:
                dias = 31;
                break;
            case 3:
            case 5:
            case 8:
            case 10:
                dias = 30;
                break;
            default:
                dias = 28;
                break;
        }
        if (mes == 1 && (1950 + año) % 4 == 0) {
            dias++;
        }
        comboDia.removeAllItems();
        for (int i = 1; i <= dias; i++) {
            comboDia.addItem(String.valueOf(i));
        }
    }

    private void comboAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAñoActionPerformed
        // TODO add your handling code here:
        this.actualizarComboDias();
    }//GEN-LAST:event_comboAñoActionPerformed

    private void comboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesActionPerformed
        // TODO add your handling code here:
        this.actualizarComboDias();
    }//GEN-LAST:event_comboMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonRegistro;
    private javax.swing.JRadioButton buttonSexoF;
    private javax.swing.JRadioButton buttonSexoM;
    private javax.swing.JRadioButton buttonSexoNoId;
    private javax.swing.JComboBox<String> comboAño;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JComboBox<String> comboCiExp;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboEstadoCivil;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JComboBox<String> comboPais;
    private javax.swing.JLabel fotoPerfilFija;
    private javax.swing.JLabel iconAtras;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelApellM;
    private javax.swing.JLabel labelApellP;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelCi;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEstCivil;
    private javax.swing.JLabel labelFechaNac;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPais;
    private javax.swing.JLabel labelSueldo;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelFecha;
    private javax.swing.JPanel panelSexo;
    private javax.swing.JPopupMenu popupMenuAnterior;
    private javax.swing.JTextField textApellM;
    private javax.swing.JTextField textApellP;
    private javax.swing.JTextField textCi;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextArea textDireccion;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textSueldo;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
